name = "BettingStrategy-MonteCarlo"
badges = ["travis", "codecov", "metacpan"]
authority="cpan:NQOUNET"

module_maker="ModuleBuildTiny"
static_install = "auto"
markdown_maker = "Pod::Markdown::Github"
